#!/usr/bin/env node
import { spawn } from "child_process";
import { statSync, existsSync } from "fs";
import { CONFIG, getSiliconFlowApiKey } from "./config.js";

export async function transcribeAudio(audioPath) {
  const apiKey = getSiliconFlowApiKey();
  if (!apiKey) {
    return { error: "未设置 SILICON_FLOW_API_KEY" };
  }

  const stats = statSync(audioPath);
  if (stats.size > CONFIG.MAX_FILE_SIZE) {
    return { error: `文件大小 ${(stats.size / (1024 * 1024)).toFixed(2)}MB 超过 50MB 限制` };
  }

  return new Promise((resolve, reject) => {
    const proc = spawn("curl", [
      "-X", "POST",
      "-H", `Authorization: Bearer ${apiKey}`,
      "-F", `file=@${audioPath}`,
      "-F", `model=${CONFIG.TRANSCRIPTION_MODEL}`,
      CONFIG.SILICON_FLOW_API_URL,
    ], { stdio: "pipe" });

    let output = "";
    proc.stdout.on("data", (d) => (output += d.toString()));
    proc.on("close", (code) => {
      output = cleanCurlOutput(output);
      if (code === 0) {
        try {
          const result = JSON.parse(output);
          if (result.text) {
            resolve({ text: result.text });
          } else if (result.error) {
            resolve({ error: result.error });
          } else {
            resolve({ text: output });
          }
        } catch {
          resolve({ text: output });
        }
      } else {
        reject(new Error(`转写失败，退出码: ${code}`));
      }
    });
  });
}

function cleanCurlOutput(output) {
  const lines = output.split('\n');
  const jsonLines = [];

  for (const line of lines) {
    if (line.trim() === '' || line.startsWith('%') || /^\d+\s+\d+/.test(line)) {
      continue;
    }
    if (line.startsWith('{')) {
      jsonLines.length = 0;
    }
    jsonLines.push(line);
    if (line.endsWith('}')) break;
  }

  if (jsonLines.length > 0) {
    return jsonLines.join('\n');
  }

  const match = output.match(/\{[\s\S]*\}/);
  return match ? match[0] : output;
}

export async function formatTranscriptMd(text, title, videoUrl, videoInfo = null) {
  let yaml = `---
title: "${title.replace(/"/g, '\\"')}"
date: "${new Date().toISOString().split('T')[0]}"`;
  if (videoUrl) yaml += `\nvideoUrl: "${videoUrl}"`;
  if (videoInfo?.duration) yaml += `\nduration: "${videoInfo.duration}"`;
  if (videoInfo?.viewCount) yaml += `\nviews: ${videoInfo.viewCount}`;
  yaml += `\n---\n\n# ${title}\n\n${text.trim()}\n\n---\n\n*Generated by video-searcher / Silicon Flow FunAudioLLM*\n*Date: ${new Date().toLocaleString('zh-CN')}*`;

  return yaml;
}

export function getTranscriptionResult(result) {
  if (result.error) {
    return { success: false, error: result.error };
  }
  if (result.text) {
    return { success: true, text: result.text };
  }
  return { success: false, error: "未知错误" };
}

export async function findAudioFile(dir) {
  try {
    const { readdirSync } = await import("fs");
    const entries = readdirSync(dir);

    const priority = ['.mp3', '.wav', '.m4a', '.ogg', '.flac', '.webm'];
    for (const ext of priority) {
      const audio = entries.find(e => e.endsWith(ext));
      if (audio) return `${dir}/${audio}`;
    }
    return null;
  } catch {
    return null;
  }
}
